want_go = ['sichuan', 'yunnan', 'xizhang', 'neineng', 'hainan']
print("I want to go:")
print(want_go)
print(sorted(want_go))
print(want_go)
print(sorted(want_go, reverse = True))
print(want_go)
want_go.reverse()
print(want_go)
want_go.reverse()
print(want_go)
want_go.sort()
print(want_go)
want_go.sort(reverse = True)
print(want_go)
